package Monitoring;
public class UI {

    private Report[] reports;
    
    /**
     * Show a list of the reports generated by the monitoring service
     * @return a list of the reports generated
     */
    public Report[] showAllReport(){
        return reports;
    }

    /**
     * Displays selected report on screen
     * @param report the report to be displayed
     */
    public void displayReport(Report report){

    }

    /**
     * Allows admins to login using credentials
     * @param username the username set by admin
     * @param password the password set by admin
     */
    public void login(String username, String password) {
        
    }
}
